# Generated by Django 3.2.12 on 2023-09-28 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='instructions',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='lesson',
            name='parameters',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.PositiveSmallIntegerField(null=True)),
                ('instruction', models.TextField(max_length=100, null=True)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Steps', to='workspace.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LessonSession',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='session_id')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workspace.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
