# Generated by Django 3.2.12 on 2023-09-28 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_auto_20230928_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workspace.lesson'),
        ),
    ]
