# Generated by Django 3.2.12 on 2023-12-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='substance',
            field=models.JSONField(),
        )
    ]
