# Generated by Django 3.2.12 on 2023-12-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_auto_20231210_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
