# Generated by Django 3.2.12 on 2023-12-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_reaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitrationExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_solution_volume', models.FloatField()),
                ('titrant_concentration', models.FloatField()),
                ('initial_solution_concentration', models.FloatField()),
                ('total_titrant_volume', models.FloatField(blank=True, null=True)),
                ('final_solution_volume', models.FloatField(blank=True, null=True)),
                ('final_solution_concentration', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(default='', upload_to='videos/'),
            preserve_default=False,
        ),
    ]
