# Generated by Django 3.2.12 on 2024-03-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_auto_20231229_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='procedure',
            field=models.JSONField(null=True),
        ),
    ]
