# Generated by Django 3.2.12 on 2024-05-01 12:11

from django.db import migrations, models
import src.workspace.models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_auto_20240430_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.FileField(default='default.png', upload_to='lessons', validators=[src.workspace.models.validate_file_extension]),
        ),
    ]
