# Generated by Django 3.2.12 on 2024-05-14 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.workspace.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0009_alter_lesson_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.FileField(default='default.svg', upload_to='lessons', validators=[src.workspace.models.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[src.workspace.models.validate_instructor]),
        ),
    ]
