# Generated by Django 3.2.12 on 2024-05-16 09:16

from django.db import migrations, models
import src.workspace.models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0010_auto_20240514_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.CharField(blank=True, default='default.svg', max_length=256, null=True, validators=[src.workspace.models.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.CharField(blank=True, default='default.mp4', max_length=256, null=True, validators=[src.workspace.models.validate_video_file_extension]),
        ),
    ]
