# Generated by Django 3.2.12 on 2024-05-19 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.workspace.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0012_auto_20240519_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[src.workspace.models.validate_instructor]),
        ),
    ]
