# Generated by Django 3.2.12 on 2026-09-30 16:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0016_lesson_moodle_assignment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TitrationExperiment',
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='measurements',
            field=models.JSONField(blank=True, default=dict, help_text='Student telemetry and measurement data', null=True),
        ),
        migrations.AlterField(
            model_name='lessonsession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='session_id'),
        ),
    ]
