# Generated by Django 3.2.12 on 2024-05-18 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20240516_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.CharField(default=datetime.datetime(2024, 5, 18, 20, 49, 55, 136171), max_length=50, null=True),
        ),
    ]
