# Generated by Django 3.2.12 on 2024-05-19 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.CharField(default=datetime.datetime(2024, 5, 19, 8, 53, 53, 677026), max_length=50, null=True),
        ),
    ]
