# Generated by Django 3.2.12 on 2024-03-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparatus',
            name='image',
            field=models.ImageField(default='default.png', upload_to='apparatus'),
        ),
        migrations.AddField(
            model_name='substance',
            name='image',
            field=models.ImageField(default='default.png', upload_to='substances'),
        ),
    ]
