# Generated by Django 3.2.12 on 2024-03-02 15:09

from django.db import migrations, models
import src.workbench.models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0002_auto_20240302_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='image',
            field=models.FileField(default='default.png', upload_to='substances', validators=[src.workbench.models.validate_svg]),
        ),
    ]
