# Generated by Django 3.2.12 on 2024-05-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0004_auto_20240302_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='image',
            field=models.CharField(blank=True, default='default.svg', max_length=256, null=True),
        ),
    ]
