# Generated by Django 3.2.12 on 2024-05-16 09:16

from django.db import migrations, models
import src.workbench.models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0005_alter_substance_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apparatus',
            name='image',
            field=models.CharField(blank=True, default='default.svg', max_length=256, null=True, validators=[src.workbench.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='substance',
            name='image',
            field=models.CharField(blank=True, default='default.svg', max_length=256, null=True, validators=[src.workbench.models.validate_file_extension]),
        ),
    ]
