# Generated by Django 3.2.12 on 2026-09-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0006_auto_20240516_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='phValue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='substance',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
