# Generated by Django 3.2.12 on 2026-09-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0007_substance_float_ph_and_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparatus',
            name='precision',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
